version: '3.9'

services:
  server-migrate:
    build:
      context: .
    volumes:
      - ./dist:/usr/src/app/migrations:delegated,z
    environment:
      - DATABASE=mysql://root:secret@host.docker.internal:3306/serlo?query
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  # START: MySQL service
  mysql:
    build:
      context: mysql/docker-container
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - '3306:3306'
  # END: MySQL service
