version: '3.9'

services:
  server-migrate:
    build:
      context: .
    environment:
      - DATABASE=mysql://root:secret@mysql:3306/serlo
  mysql:
    build:
      context: mysql/docker-container
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - '3306:3306'
