version: '3.9'

services:
  server-migrate:
    build:
      context: .
    environment:
      - DATABASE=mysql://root:secret@mysql:3306/serlo
  mysql:
    image: eu.gcr.io/serlo-shared/serlo-mysql-database:0.3.1
    platform: linux/x86_64
    pull_policy: always
    ports:
      - '3306:3306'
