version: '3.9'

services:
  server-migrate:
    build:
      context: .
    env_file:
      - .env
      - .env-docker
    extra_hosts:
    - "host.docker.internal:host-gateway"

  mysql:
    image: eu.gcr.io/serlo-shared/serlo-mysql-database:latest
    platform: linux/x86_64
    ports:
      - '3306:3306'

  redis:
    image: redis:6.0
    ports:
      - '6379:6379'
