name: Test whether migrations have been run successfully
runs:
  using: composite
  steps:
    # With the following command we check that the migration
    # "20201023104526-update-subjects" was run
    # successfully
    - run: yarn mysql:list-migrations | grep
        20201023104526-update-subjects
      shell: bash
