name: CI Checks
on: [push, merge_group]

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:prettier

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn test

  migrate_ts:
    name: Migrations succeed after calling directly from `src`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - uses: serlo/configure-repositories/actions/setup-mysql@main
      - run: yarn mysql:delete-all-migrations
      - run: yarn migrate:ts
      - uses: ./.github/actions/test-migrations

  migrate_docker:
    name: Migrations succeed after running in docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - uses: serlo/configure-repositories/actions/setup-mysql@main
      - run: yarn mysql:delete-all-migrations
      - run: yarn migrate:docker
      - uses: ./.github/actions/test-migrations
