name: CI Checks
on: [push, merge_group]

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn --check-cache

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:prettier

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn start
      - run: yarn test

  migrate_ts:
    name: Migrations succeed after calling directly from `src`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn start
      - uses: serlo/configure-repositories/actions/setup-mysql@main
      - run: yarn migrate:all
      - run: ./scripts/check_all_migrations_run.sh

  migrate_docker:
    name: Migrations succeed after running in docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn start
      - uses: serlo/configure-repositories/actions/setup-mysql@main
      - run: yarn migrate:docker
      - run: ./scripts/check_all_migrations_run.sh
