name: CI Checks
on: [push, merge_group]

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn lint:prettier

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn test

  migrate_ts:
    name: Migrations succeed after calling directly from `src`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn start
      - run: ./mysql/scripts/wait-for-mysql.sh
      - run: yarn migrate:ts
      # With the following command we check that the migration
      # "20220625202000-convert-important-and-blockquote-to-box" was run
      # successfully
      - run:
          yarn mysql:list-migrations | grep
          20220625202000-convert-important-and-blockquote-to-box
