name: CI Checks
on: [push, merge_group]

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: yarn lint:prettier

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: yarn test

  migrate_ts:
    name: Migrations succeed after calling directly from `src`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-mysql
      - run: yarn migrate:ts
      # With the following command we check that the migration
      # "20220625202000-convert-important-and-blockquote-to-box" was run
      # successfully
      - run:
          yarn mysql:list-migrations | grep
          20220625202000-convert-important-and-blockquote-to-box

  migrate_docker:
    name: Migrations succeed after running in docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-mysql
      - run: yarn migrate:docker
      # With the following command we check that the migration
      # "20220625202000-convert-important-and-blockquote-to-box" was run
      # successfully
      - run:
          yarn mysql:list-migrations | grep
          20220625202000-convert-important-and-blockquote-to-box
