name: Docker
on:
  pull_request:
  merge_group:
env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the api-db-migration image
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          file: ./Dockerfile
          tags: api-db-migration:PR-${{ env.PR_NUMBER }}
      - name: Test for node in the api-db-migration image
        run:
          docker run --entrypoint='' --rm api-db-migration:PR-${{ env.PR_NUMBER
          }} node --version
