name: Image
on:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY_CONTAINER_REGISTRY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: '372.0.0'
      - run: gcloud auth configure-docker
      - run: yarn --immutable --immutable-cache
      - run: yarn push-image
